# Generated by Django 5.2 on 2025-04-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
                ("subject", models.CharField(default="No subject", max_length=255)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
