# Generated by Django 5.2 on 2025-04-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactmessage",
            name="subject",
            field=models.CharField(default="No subject", max_length=255),
        ),
    ]
