# Generated by Django 5.2 on 2025-04-28 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_contactmessage_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название рецепта"),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("ingredients", models.TextField(verbose_name="Ингредиенты")),
                ("instructions", models.TextField(verbose_name="Инструкции")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "likes",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество лайков"
                    ),
                ),
            ],
        ),
    ]
