# Generated by Django 5.2 on 2025-04-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_recipe_likes_recipe_author_recipelike"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="recipe",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="recipes/", verbose_name="Изображение"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="main.category",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
    ]
