# Generated by Django 5.2 on 2025-04-30 07:01

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_category_recipe_image_recipe_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="instructions",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Инструкции"),
        ),
    ]
