# Generated by Django 5.2 on 2025-05-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_remove_recipe_ingredients_ingredient"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="cook_time_hours",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Время готовки (часы)"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="cook_time_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Время готовки (минуты)"
            ),
        ),
    ]
