# Generated by Django 5.2 on 2025-05-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_recipe_cook_time_hours_recipe_cook_time_minutes"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="active_time_hours",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ваше время (часы)"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="active_time_minutes",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Ваше время (минуты)"
            ),
        ),
    ]
