# Generated by Django 5.2 on 2025-05-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_ingredient_quantity_alter_ingredient_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Вес (г)",
            ),
        ),
    ]
