# Generated by Django 5.2 on 2025-05-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_alter_ingredient_quantity_alter_ingredient_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="quantity",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Количество"
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="weight",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Вес (г)"
            ),
        ),
    ]
