# Generated by Django 5.2 on 2025-05-06 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_alter_ingredient_quantity_alter_ingredient_weight"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="dislikes",
        ),
    ]
